### ISSUE TITLE
Can we change the url to nr-fds-theme? Or is that crazy?

### ISSUE THREAD

**Issue by jackwingsam** [bcgov/nr-theme#64]
Can we change the url/repo name to nr-fds-theme? Or is that crazy at this point?
@DerekRoberts

**Comment by DerekRoberts** [comment]
@jackwingsam Ha, sure!  Whatever your team decides we do.  :D

**Comment by jackwingsam** [comment]
Looks like while I was on vacation, we got approval to change from FSA to FDS

**Comment by DerekRoberts** [comment]
Welcome back @jackwingsam!  :)  ...Let's talk to @MCatherine1994 about making this change.

**Comment by MCatherine1994** [comment]
Hi Jack @jackwingsam, changing url is doable. Just wondering since we already published some packages that teams are sharing for the stylesheet. If we change the repo name, we might want to change the package name as well?

**Comment by jackwingsam** [comment]
i really don't know how to answer the part about the packages. 

the name change overall is not a high priority thing. but slightly higher priority now that Chantelle got the name change approved. what's a good timeline that fits your schedule?

**Comment by DerekRoberts** [comment]
@jackwingsam Let's leave that to @MCatherine1994.  I'm mostly here for support and/or to fill in any gaps.

**Comment by jackwingsam** [comment]
yeah, sorry i didn't tag anyone. my last comment was meant to ask @MCatherine1994 to pick a timeline that best suits her pre-existing workload

**Comment by MCatherine1994** [comment]
sure, I'll bring this to our dev meetup this Thursday cause the package naming will impact the teams that are currently using it. And will target do the change next Monday. Thanks!

**Comment by MCatherine1994** [comment]
Morning @jackwingsam @DerekRoberts, I wonder do we need to include "fds" in our repo name? Or maybe we can call it "nr-common-theme", so we don't need to worry about the team name in the future?

**Comment by DerekRoberts** [comment]
@MCatherine1994 I like that idea!  Departments get renamed all the time in gov.  Plus common says a lot.  :)

**Comment by jackwingsam** [comment]
I'm ok with a more generic name but maybe something more specific to forestry? We know there are other NR sector teams (like ENV and even with FOR/WLRS) also doing their own design systems. We tried to join forces but they didn't want to...

**Comment by MCatherine1994** [comment]
how about nr-forest-theme? or any other suggestion? @jackwingsam @DerekRoberts

**Comment by DerekRoberts** [comment]
Ideally we'd build components that all of NR can use.  Most of my tools are for general consumption, not just gov.

**Comment by MCatherine1994** [comment]
yeah, I agree. If other teams want a different theme, they can name their repo differently

**Comment by MCatherine1994** [comment]
I'll put this on hold for now until Andrea is back from the vacation and it's not that urgent, then we can discuss which name want to use.

**Comment by jackwingsam** [comment]
> Ideally we'd build components that all of NR can use. Most of my tools are for general consumption, not just gov. `nr-theme`!

i like to think that way too, building for all of gov, but we did shop what we're doing with other NR teams and they were not satisfied with it. 

the other thing that makes me not that comfortable with a generic nr-theme repo name is that we made a lot of decisions that are not in line with the rest of BCGov/GCPE. for example the blue that we have for the buttons across all of our login pages and headers on the content pages is not a normal BC Gov blue. we made some decisions that were only focused on FSA/FDS apps. 

i agree with @MCatherine1994, let's wait for Andrea

**Comment by MCatherine1994** [comment]
Just to provide an update for this issue. I checked the repos in bcgov organization, don't see any other repo named with "nr" or "theme", also chatted with Andrea, we should be good to use "nr-theme". If other teams also work on other design systems, they can call their repo a different name.

**Comment by jackwingsam** [comment]
Thanks @MCatherine1994 
@alkolot is the one who's going to have to interface with other nr design teams
