### ISSUE TITLE
Change the fields' label to use "primary-text" instead of "secondary-text"

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-theme#78]
Hi folks!

According to the title, we expect the labels color to be changed from `secondary-text` to `primary-text`.

This is currently listed in the [change log](https://www.figma.com/file/KDXuYanyOsBCM5vpPmNvGf/FSA-Design-System?type=design&node-id=14622-342600&mode=design&t=LPCemh5c4b35EEYB-0).

This issue is also blocking a task for us at SPAR...

Thanks!

**Comment by jackwingsam** [comment]
this ticket wasn't assigned to anyone. who should be doing this?

@mgaseta we also have a new change log here: https://github.com/orgs/bcgov/projects/45

I'm going to re-create this ticket in the Proposals column and tag @MCatherine1994 @jazzgrewal

**Comment by mgaseta** [comment]
Created a new one tracked by a ticket on the board and tagged them, I'll close this one.
