### ISSUE TITLE
Change the fields' label to use "primary-text" color instead of "secondary-text"

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-theme#97]
According to the title, we expect the labels color to be changed from secondary-text to primary-text.

This is currently listed in the [change log](https://www.figma.com/file/KDXuYanyOsBCM5vpPmNvGf/FSA-Design-System?type=design&node-id=14622-342600&mode=design&t=LPCemh5c4b35EEYB-0).

As requested by Jack on issue [#78](https://github.com/bcgov/nr-theme/issues/78), tagging @MCatherine1994 and @jazzgrewal

Jack copypasta from Figma - July 8, 2023

**Enhancement:**
Increase text inputs’ label size and color contrast

**Reason:**
Users found the input’s labels difficult to read and distinguish

**Discussed**
* Users might find it better to ready and perceive the inputs’ labels if the color contrast and font size were enhanced
* We need to increase the labels’ legibility
*Changing the font size and color could have an impact on text and color hierarchy, making it very similar to the input text and body text
*Having a label text to the body text might not happens in some scenarios

**Resolution**
* We will change the label’s color style from “text-secondary” to “text-primary”
* We will text to see if this change will be enough to improve the legibility.
* If not, more changes might be needed and will be discussed further.

**What changed**
Labels color style

Text color will change
* was: text-secondary
* new: text-primary

Components:
* Checkbox
* Date picker
* Form
* Dropdown
* Number input
* Password input
* Radio button
* Select
* Slider
* Text input
* Text area
* Toggle

Themes:
* Light theme
* Dark theme

**Participants:**
Andrea Kolot
Jack Sam
Olga Liberchuk
Michelly Marsoleta
Marina Carvalho
Maria Fernanda Ferreira
Maria Eduarda Guimarães 
Sabina Donnelly

**Comment by jackwingsam** [comment]
@alkolot can we rush-approve this one and move it to the "Approved" backlog?

This was the item that Michelley created in July 2023 in the Figma change log (linked above). 

Michelley's comment from that time was that it was already changed in the Figma library so we can skip the "in progress in Figma) column. This can go directly to the "in progress in code" once someone can take it on.

**Comment by alkolot** [comment]
Yes, let's move it to approved.

**Comment by jackwingsam** [comment]
I don't know how much work this is so can @MCatherine1994 or @jazzgrewal coordinate with @mgaseta? This was listed as a blocker for Evergreen in [Issue 78](https://github.com/bcgov/nr-theme/issues/78)

**Comment by MCatherine1994** [comment]
Think once this got approved and changes have been made in Figma, then we can assign the developer in Evergreen to implement the code change as they need. @craigyu

**Comment by jackwingsam** [comment]
Changes should have been made in Figma already during the summer. @craigyu can you please confirm with Michelley?

**Comment by mgaseta** [comment]
Sure, I can take it, just need the permission.

**Comment by craigyu** [comment]
@MCatherine1994 can we give @mgaseta write access please?

**Comment by jackwingsam** [comment]
@DerekRoberts if Catherine is busy

**Comment by jackwingsam** [comment]
nevermind, it looks like i could have done it. just invited @mgaseta to have "write" permissions

**Comment by MCatherine1994** [comment]
sorry just get this, I have the GitHub notification in another email account, maybe next time just ping me in teams, thanks!!
